version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_adb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: db_analysis1
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
      - ./исходные данные:/csv-data


volumes:
  pgdata:
